import 'package:flutter/material.dart';

class ColorConstants {
  static const Color primaryColor = Color(0XFF262525);
  static const Color secondaryColor = Color(0XFFf2eded);
  static const Color lightBrown = Color.fromARGB(255, 253, 249, 247);
  static const Color cream = Color.fromARGB(255, 250, 242, 239);
  static const Color lightScaffoldBackgroundColor = Color(0XFFF3EbF7);
  static const Color darkScaffoldBackgroundColor = Color(0XFF736565);
  static const Color cardLightColor = Color(0XFFD9CCE0);
  static const Color cardDarkColor = Color(0XFFf2eded);
  static const Color darkPrimaryContainerColor = Color(0XFFecebfa);
  static const Color colorWhite = Color(0XFFFFFFFF);
  static const Color colorBlack = Color(0XFF000000);
  static const Color hintColorLight = Color(0XFFb4b3b5);
  static const Color hintColorDark = Color(0XFFF5F0F7);
  static const Color focusColorLight = Color(0XFFFFFFFF);
  static const Color focusColorDark = Color(0XFFE9E6EB);
  static const Color transparent = Colors.transparent;
  static const Color fontBlackColor = Color(0XFF252525);
  static const Color fontTitleLightColor = Color(0XFF050505);
  static const Color fontTitleDarkColor = Color(0XFFF2EDF5);
  static const Color fontSubTitleLightColor = Color(0XFF7F7D80);
  static const Color fontSubTitleDarkColor = Color(0XFFF5F0F7);
  static const Color fontGreyColor = Color(0XFF828282);
  static const Color errorRed = Color(0XFFDA0000);
  static const Color buttonBackgroundColor = Color(0XFFFFB703);
  static const Color selectionRedColor = Color(0XFFFE4444);
  static const Color shadowColor = Color(0XFFFAFAFA);
  static const Color lightGrey = Color(0XFFF5F5F5);
  static const Color lighterGrey = Color(0XFF504c54);
  static const Color darkGrey = Color(0XFF2b2a2b);
  static const Color mediumGrey = Color(0XFFA2A2A2);
  static const Color successGreen = Color(0XFF00BD35);
  static const Color todoCard = Color(0XFFf7dfc3);
  static const Color ongoingCard = Color(0XFFa9dcf5);
  static const Color completedCard = Color(0XFFD5FCD2);
  static const Color todoCount = Color(0XFFf58505);
  static const Color ongoingCount = Color(0XFF05a3f2);
  static const Color completedCount = Color(0XFF16fa05);
  static const Color cyan = Color.fromRGBO(198, 221, 219, 1.0);
  static const Color greyColorC3 = Color(0xFFC3C3C3);
  static const Color buttonGradient = Color(0xFF530470);
  static const Color darkBrown = Color.fromARGB(255, 151, 115, 103);
  static const Color tabBarColor = Color.fromARGB(255, 226, 178, 160);
}
